import Entry from "../interfaces/Entry";

var testEntries: Array<Entry> = [
	{
		user: "jedd",
		id: 1,
		itemDate: "2020-12-2",
		timeConsumed: "15:43",
		itemDesc: "Cheese Burger",
		consumedLocation: "In Maccas carpark",
		consumptionCompany: "Alone",
		feelingPrior: "Stress, uneasy, desperate",
		feelingPost: "gross, greasy, slimey",
		selfTalk: "I am a gross little piggy for eating this",
		otherComment: "I got extra pickles",
	},
	{
		user: "jedd",
		id: 2,
		itemDate: "2024-6-2",
		timeConsumed: "4:43",
		itemDesc: "Leg of Ham",
		consumedLocation: "Office bathroom cubical",
		consumptionCompany: "Pattrick",
		feelingPrior: "Sneaky, subversive, guilty",
		feelingPost: "successful, strong, bold",
		selfTalk: "I have never seen Pattrick eat so much, it kind of intimidated me",
		otherComment: "Honey glaze on the ham",
	},
	{
		user: "jedd",
		id: 3,
		itemDate: "2024-12-2",
		timeConsumed: "7:43",
		itemDesc: "15 raw cellery sticks",
		consumedLocation: "In the dark in my Kitchen",
		consumptionCompany: "With my wife, also in the dark",
		feelingPrior: "glorious, free, ready",
		feelingPost: "satisfied, fixed, whole",
		selfTalk: "I am god incarnate",
		otherComment: "the crunch was amazing",
	},
	{
		user: "craig",
		id: 1,
		itemDate: "2024-12-2",
		timeConsumed: "7:43",
		itemDesc: "15 raw cellery sticks",
		consumedLocation: "In the dark in my Kitchen",
		consumptionCompany: "With my wife, also in the dark",
		feelingPrior: "glorious, free, ready",
		feelingPost: "satisfied, fixed, whole",
		selfTalk: "I am god incarnate",
		otherComment: "the crunch was amazing",
	},
];

export default testEntries;